dist: bionic

language: python

python:
  - "3.7"

# Commands to install dependencies:
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install codecov

script:
  - pytest --cov=mydata

after_success:
  - codecov
